name: langen
description: A simple package to generate lang json keys to dart Strings
version: 0.0.1
homepage: https://github.com/yusubx/Packages

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_config: ^0.4.2
  build_runner: ^1.9.0

flutter: null



